AWSTemplateFormatVersion: 2010-09-09
Resources:
  # Role
  GetUserLambdaRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  GetUserLambdaPolicies:
    DependsOn:
      - UsersTable
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Join ["-", [!Ref App, !Ref Stage, "UsersServiceAccessPolicy"]]
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
          -
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
            Resource:
              - !GetAtt UsersTable.Arn
      Roles:
        - !Ref GetUserLambdaRole
        
  # Lambda
  GetUserFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - UsersServiceApi
    Properties:
      FunctionName: !Join ["-", [!Ref App, !Ref Stage, "getUser"]]
      Description: Get user
      Handler: index.handler
      Code: ./functions/getUser/
      Runtime: nodejs6.10
      Role: !GetAtt GetUserLambdaRole.Arn
      Environment:
        Variables: 
          UsersTable: !Ref UsersTable
          AllowOrigin: !Ref AllowOrigin
  GetUserFunctionPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref GetUserFunction
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Join ["", ["arn:aws:execute-api:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":*/*/GET/users"]]
  
  # Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Join ["-", [!Ref App, !Ref Stage, "Users"]]
      AttributeDefinitions: 
        - AttributeName: mobile 
          AttributeType: S
      KeySchema: 
        - AttributeName: mobile
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # ApiGateway
  UsersServiceApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Join ["-", [!Ref App, !Ref Stage, "users"]]
  UsersApiDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - UsersGetMethod
    Properties:
      RestApiId: !Ref UsersServiceApi
      StageName: !Ref Stage
  UsersResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt UsersServiceApi.RootResourceId
      PathPart: "users"
      RestApiId: !Ref UsersServiceApi
  UsersGetMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "GET"
      AuthorizationType: "NONE"
      ResourceId: !Ref UsersResource
      RestApiId: !Ref UsersServiceApi
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Join ["", ["arn:aws:apigateway:", !Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !GetAtt GetUserFunction.Arn, "/invocations"]]
        IntegrationResponses:
          - StatusCode: 200

# Misc
Parameters:
  App:
    Type: "String"
  Stage:
    Type: "String"
  Region:
    Type: "String"
  AllowOrigin:
    Type: "String"
# Outputs
Outputs:
  UsersTableArn:
    Value: !GetAtt UsersTable.Arn
  GetUserFunctionArn:
    Value: !GetAtt GetUserFunction.Arn
  ApiUrl:
    Value: !Join ["", ["https://", !Ref UsersServiceApi, ".execute-api.", !Ref "AWS::Region", ".amazonaws.com/", !Ref Stage, "/users"]]

